* rErlang

** installation prerequisites

*** erlang

If using Ubuntu packages, erlang-dev is needed for erl_interface.

*** R

#+BEGIN_SRC
    $ sudo apt-get install r-base
#+END_SRC

To install R packages from CRAN, the CRAN mirror to use must be set.  Change the url in doc/dot-Rprofile as desired, and then:

#+BEGIN_SRC
    $ cp doc/dot-Rprofile ~/.Rprofile
#+END_SRC

For the moment at least, R packages should be installed from within R, rather than via rErlang.  e.g.:

#+BEGIN_SRC
    $ R
    > install.packages("forecast")
    >
#+END_SRC

** edit c_src/Makefile

Ensure the R paths at the top of the file are correct:

#+BEGIN_SRC
    R_INCLUDE_DIR := /usr/share/R/include
    R_HOME := /usr/lib/R
#+END_SRC

** build

*** with make

#+BEGIN_SRC
    $ make
#+END_SRC

This outputs erlang beam files to ./ebin/.

*** with rebar3

#+BEGIN_SRC
    $ rebar3 compile
#+END_SRC

This creates a new directory _build/ containing all artefacts.

** run

Example usage:

#+BEGIN_SRC erlang

    $ ./start_erl_node.sh  # if built with make
    $ rebar3 shell  # if built with rebar3
    Erlang/OTP 18 [erts-7.0] [source] [64-bit] [async-threads:10] [kernel-poll:false]
    Eshell V7.0  (abort with ^G)
    
    (node01@localhost)1> eri:start().
    "."
    true
    
    (node01@localhost)2> eri:connect().
    {ok,0}
    
    (node01@localhost)3> eri:eval("x <- c(12,34,56,78,90)").
    {ok,'REALSXP',[12.0,34.0,56.0,78.0,90.0]}
    
    (node01@localhost)4> eri:eval("mean(x)").
    {ok,'REALSXP',[54.0]}
    
    (node01@localhost)5> eri:stop().
    stop

#+END_SRC

Note that:

- This is an interactive session.  Command #3 sets a variable x, then command #4 uses that variable.

** warnings and caveats

*** NaN and Infinity float values

R and Erlang use slightly different definitions of floating-point number.  In particular, the R floating-point number type defines NaN (not a number") and infinity values; Erlang's does not.  An R NaN, sent from R to Erlang, becomes invalid data, and crashed Erlang's binary_to_term/1.  See:

Why is this erlang binary failing binary_to_term/1?
https://stackoverflow.com/questions/38684941/why-is-this-erlang-binary-failing-binary-to-term-1

To protect Erlang from NaNs (and Infinities), the R function safetify(x, default) is provided, in priv/rscripts.utils.R.  This takes a vector x and a default.  It returns a copy of x, with all instances of NaN replaced by the default.

Used in an R session:

#+BEGIN_SRC erlang

    > x <- c(1, 2, 3, NaN, 5)
    > x
    [1]   1   2   3 NaN   5
    > mean(x)
    [1] NaN
    > y <- safetify(x, 0)
    > y
    [1] 1 2 3 0 5
    > mean(y)
    [1] 2.2

#+END_SRC

Used in an erlang session:

#+BEGIN_SRC erlang

    %% TODO

#+END_SRC
